//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBulletJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalE
    {
        public int JournalId { get; set; }
        public string JournalTitle { get; set; }
        public string PicUrl { get; set; }
    }
}
